# Generated by Django 5.2.7 on 2025-10-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspaceinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceinvitation',
            name='recipient_name',
            field=models.CharField(default='Guest', help_text='Full name of the person being invited', max_length=200),
        ),
        migrations.AddField(
            model_name='workspaceinvitation',
            name='recipient_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number for SMS notification (optional)', max_length=20),
        ),
    ]
