# Generated by Django 5.2.6 on 2025-11-01 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspaceinvitation_recipient_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='File or link name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('file_type', models.CharField(choices=[('upload', 'Uploaded File'), ('link', 'External Link')], default='upload', max_length=10)),
                ('file', models.FileField(blank=True, help_text='Upload a file', null=True, upload_to='workspace_files/%Y/%m/%d/')),
                ('external_url', models.URLField(blank=True, help_text='Link to external file (Google Drive, Dropbox, etc.)', max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspace_files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
