# Generated by Django 6.0.1 on 2026-01-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_workspacefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('pm', 'Project Manager'), ('member', 'Member')], db_index=True, default='member', max_length=20),
        ),
    ]
