# Generated by Django 5.2.7 on 2025-11-08 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_organization',
            field=models.ForeignKey(blank=True, help_text="User's currently active organization", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_members', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='[DEPRECATED] Use current_organization instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.organization'),
        ),
        migrations.CreateModel(
            name='UserOrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', help_text="User's role in this organization", max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Organization Membership',
                'verbose_name_plural': 'User Organization Memberships',
                'db_table': 'user_organization_memberships',
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(help_text='Organizations this user belongs to', related_name='all_members', through='accounts.UserOrganizationMembership', to='accounts.organization'),
        ),
    ]
