# Generated by Django 5.2.7 on 2025-11-08 22:03

from django.db import migrations


def migrate_existing_organizations(apps, schema_editor):
    """
    Migrate existing user.organization relationships to UserOrganizationMembership.
    - If user created the organization, they become 'owner'
    - Otherwise, they become 'member'
    - Set current_organization to their existing organization
    """
    User = apps.get_model('accounts', 'User')
    Organization = apps.get_model('accounts', 'Organization')
    UserOrganizationMembership = apps.get_model('accounts', 'UserOrganizationMembership')

    for user in User.objects.filter(organization__isnull=False):
        # Determine role: owner if they created it, otherwise member
        if user.organization.created_by_id == user.id:
            role = 'owner'
        else:
            role = 'member'

        # Create membership (use get_or_create to avoid duplicates)
        UserOrganizationMembership.objects.get_or_create(
            user=user,
            organization=user.organization,
            defaults={'role': role}
        )

        # Set current_organization to their existing organization
        user.current_organization = user.organization
        user.save(update_fields=['current_organization'])


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by clearing memberships and current_organization.
    Note: This will lose role information.
    """
    User = apps.get_model('accounts', 'User')
    UserOrganizationMembership = apps.get_model('accounts', 'UserOrganizationMembership')

    # Clear all memberships
    UserOrganizationMembership.objects.all().delete()

    # Clear current_organization
    User.objects.update(current_organization=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_current_organization_alter_user_organization_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_organizations, reverse_migration),
    ]
